### ISSUE TITLE
Cursor position inside JS, style or &nbps;

### ISSUE THREAD

**Issue by thomich** [christiaan/tinymce-codemirror#2]
Hey

I checked and also wrote comment on a bug at TinyMCE:
https://github.com/tinymce/tinymce/issues/2009

i saw also the following, if in code you place the cursor inside a &nbps; and click ok, it makes the &nbps; visible in tinymce, see screenshot:
![shot-selection-004](https://cloud.githubusercontent.com/assets/4398840/11361242/6991ff2c-928c-11e5-9622-bf1091102d05.png)

![shot-selection-005](https://cloud.githubusercontent.com/assets/4398840/11361244/6dfa565e-928c-11e5-8611-862e615c0ca0.png)

opening code again:
![shot-selection-006](https://cloud.githubusercontent.com/assets/4398840/11361259/93970f74-928c-11e5-96af-9bcc470d4df2.png)

any hint or solution would be fine...

thanks
thomi

**Comment by thomich** [comment]
found a little, fast workaround about cursor posion inside &nbps; or also in &uuml;/&auml;/&ouml; and all of those..
add a extra line in function findDepth, which is used to not place the cursor if cursor position in codemirror is inside tags.

extra line is: case '&': depth++; break;

full function:

```
function findDepth(haystack, needle)
{
    "use strict";

    var idx = haystack.indexOf(needle), depth = 0, x;
    for (x = idx -1; x >= 0; x--) {
        switch(haystack.charAt(x)) {
            case '<': depth--; break;
            case '>': depth++; break;
            case '&': depth++; break;
        }
    }
    return depth;
}
```

tested and now, if inside in any of the above html entities, it does not place the cursor in tinymce editor...

not the best solution, cause needle does contain the placeholder, now cursor won't be placed back to tinymce any more...
placeholder:

```
&#x0;
```

UPDATE:
function updated, x= idx -1 to start not with placeholders &: 

```
for (x = idx; x >= 0; x--) {
for (x = idx -1; x >= 0; x--) {
```

**Comment by thomich** [comment]
to solve cursor position if code is open and it is inside script tag, i made this workaround in source.html function submit():

```
    var code = codemirror.getValue();
    if(code.search(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi) !== -1)
    {
        editor.setContent(codemirror.getValue().replace(cc, ''));
    }
    else
    {
        editor.setContent(codemirror.getValue().replace(cc, '<span id="CmCaReT"></span>'));
    }
```

full function:

```
// This function is called by plugin.js, when user clicks 'Ok' button
function submit()
{
    "use strict";

    var cc = '&#x0;', isDirty = codemirror.isDirty, doc = codemirror.doc;

    if (doc.somethingSelected()) {
        // Clear selection:
        doc.setCursor(doc.getCursor());
    }

    // Insert cursor placeholder (&#x0;)
    doc.replaceSelection(cc);

    var pos = codemirror.getCursor(),
        curLineHTML = doc.getLine(pos.line);

    if (findDepth(curLineHTML, cc) !== 0) {
        // Cursor is inside a <tag>, don't set cursor:
        curLineHTML = curLineHTML.replace(cc, '');
        doc.replaceRange(curLineHTML, CodeMirror.Pos(pos.line, 0), CodeMirror.Pos(pos.line));
    }

    // Submit HTML to TinyMCE:
    // Workaround to fix cursor position if inside script tag
    var code = codemirror.getValue();
    if(code.search(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi) !== -1)
    {
        editor.setContent(codemirror.getValue().replace(cc, ''));
    }
    else
    {
        editor.setContent(codemirror.getValue().replace(cc, '<span id="CmCaReT"></span>'));
    }
    editor.isNotDirty = !isDirty;
    if (isDirty) {
        editor.nodeChanged();
    }

    // Set cursor:
    var el = editor.dom.select('span#CmCaReT')[0];
    if (el) {
        editor.selection.scrollIntoView(el);
        editor.selection.setCursorLocation(el,0);
        editor.dom.remove(el);
    }
}
```

**Comment by tHerrmann** [comment]
Hi,
I have found a related issue. In case the cursor is not positioned inside an existing &lt;p&gt; tag, a new paragraph is created on close at the position of the cursor. The &lt;span&gt; element used to remember the cursor position is wrapped by tinyMCE with a &lt;p&gt; before the &lt;span&gt; is removed.

I am not sure, if the suggested solution by thomich solves this issue also. I will give it a try.

**Comment by christiaan** [comment]
Can anyone verify this is fixed by #7 ?

**Comment by chadcallahan** [comment]
I just tested and unfortunately, https://github.com/christiaan/tinymce-codemirror/pull/7 did not fix this issue.  The `&nbsp;` gets replaced with `&amp;nbsp;` after clicking Ok in the codemirror plugin; which makes `&nbsp;` visually appear in the content area.

**Comment by thomich** [comment]
workaround for the moment, until we find proper solution, idea...

**Comment by sherifzaki** [comment]
Hi
This is not working since it also happens inside any tag
and when it works inside the javascript tag, tinymce errors when you try to click on the code again plus the tinymce won't show most of the page

js error is 
TypeError: Argument 1 of Range.setStartBefore is not an object.

**Comment by thomich** [comment]
Hello @sherifzaki 
Thanks for your input.. but i can't reproduce it and my tests within tags, js, css and so on are working with this workaround.

Can you give us step by step description and code to test again?

Thanks a lot for your help
thomi

**Comment by sherifzaki** [comment]
Hi Thomas

If you click in any tag like <div …

You will have the &#x0; when you press ok and won’t close
And if your cursor is in the css code and press ok

It will close but this span will be inside the css code <span id="CmCaReT"></span>

Also the &nbsp; fix doesn’t really work if your curser is after the &

Thanks

Here is the code

<style></style>

<div id="aa_bg"><img src="/uploads/4559/images/bg.jpg" /></div>

<div class="wrap">
<div class="wrapper">
<div class="header top-fixed">
<div class="logo"><img src="/uploads/4559/images/logo.png" /></div>
</div>

<div class="center">
<div class="center-text-red">Guest Internet Service</div>
<div class="center-text-black">Let's Get You Connected</div>
<button class="center-btn colour"> Free WI-FI </button> <br /> <button class="center-btn colour"> Premium WI-FI </button></div>
</div>

<div class="bottom-fixed">
<div class="main-footer"></div>
</div>

</div>

Sherif Zaki
Senior PHP Developer

**Comment by sherifzaki** [comment]
I think there is an easy workaround
How can we focus the cursor on the end of the text in the tinymce?

Can you help me on this please?
Thanks
Sherif Zaki
Senior PHP Developer
